#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : libwpg
Version  : 0.3.4
Release  : 5
URL      : https://dev-www.libreoffice.org/src/libwpg-0.3.4.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libwpg-0.3.4.tar.xz
Summary  : Library for importing and converting Corel WordPerfect(tm) Graphics images
Group    : Development/Tools
License  : LGPL-2.1 MPL-2.0-no-copyleft-exception
Requires: libwpg-bin = %{version}-%{release}
Requires: libwpg-lib = %{version}-%{release}
Requires: libwpg-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : file
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(libwpd-0.10)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Libwpg project is a collection of library and tools to work with graphics in WPG (WordPerfect Graphics) format. WPG is the format used among others in Corel sofware, such as WordPerfect(tm) and Presentations(tm).

%package bin
Summary: bin components for the libwpg package.
Group: Binaries
Requires: libwpg-license = %{version}-%{release}

%description bin
bin components for the libwpg package.


%package dev
Summary: dev components for the libwpg package.
Group: Development
Requires: libwpg-lib = %{version}-%{release}
Requires: libwpg-bin = %{version}-%{release}
Provides: libwpg-devel = %{version}-%{release}
Requires: libwpg = %{version}-%{release}

%description dev
dev components for the libwpg package.


%package doc
Summary: doc components for the libwpg package.
Group: Documentation

%description doc
doc components for the libwpg package.


%package lib
Summary: lib components for the libwpg package.
Group: Libraries
Requires: libwpg-license = %{version}-%{release}

%description lib
lib components for the libwpg package.


%package license
Summary: license components for the libwpg package.
Group: Default

%description license
license components for the libwpg package.


%prep
%setup -q -n libwpg-0.3.4
cd %{_builddir}/libwpg-0.3.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719425148
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719425148
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libwpg
cp %{_builddir}/libwpg-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/libwpg/3704f4680301a60004b20f94e0b5b8c7ff1484a9 || :
cp %{_builddir}/libwpg-%{version}/COPYING.MPL %{buildroot}/usr/share/package-licenses/libwpg/9744cedce099f727b327cd9913a1fdc58a7f5599 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wpg2raw
/usr/bin/wpg2svg
/usr/bin/wpg2svgbatch.pl

%files dev
%defattr(-,root,root,-)
/usr/include/libwpg-0.3/libwpg/WPGraphics.h
/usr/include/libwpg-0.3/libwpg/libwpg.h
/usr/lib64/libwpg-0.3.so
/usr/lib64/pkgconfig/libwpg-0.3.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libwpg/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwpg-0.3.so.3
/usr/lib64/libwpg-0.3.so.3.0.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libwpg/3704f4680301a60004b20f94e0b5b8c7ff1484a9
/usr/share/package-licenses/libwpg/9744cedce099f727b327cd9913a1fdc58a7f5599
